[package]
name = "kun-bot"
version = "0.1.0"
edition = "2021"

[dependencies.rand]
version = "0.8.5"
default-features = false

[dependencies.serenity]
version = "0.11.5"
default-features = false
features = ["client", "gateway", "model", "rustls_backend"]

[dependencies.tokio]
version = "1.21.2"
default-features = false
features = ["rt-multi-thread"]